SET PATH=C:\Users\IanIshikawa\AppData\Local\Keil_v5\ARM\ARMCLANG\Bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Users\IanIshikawa\AppData\Local\Microsoft\WindowsApps;C:\Users\IanIshikawa\AppData\Local\Programs\Microsoft VS Code\bin
SET ARMCC6_ASMOPT=--diag_suppress=9931
SET ARMCC6_CCOPT=--diag_suppress=9931
SET ARMCC6_LINKOPT=--diag_suppress=9931
SET CPU_TYPE=TM4C1294NCPDT
SET CPU_VENDOR=Texas Instruments
SET UV2_TARGET=Target 1
SET CPU_CLOCK=0x017D7840
"C:\Users\IanIshikawa\AppData\Local\Keil_v5\ARM\ARMCLANG\Bin\ArmAsm" --Via ".\objects\gpio._ia"
"C:\Users\IanIshikawa\AppData\Local\Keil_v5\ARM\ARMCLANG\Bin\ArmAsm" --Via ".\objects\main._ia"
"C:\Users\IanIshikawa\AppData\Local\Keil_v5\ARM\ARMCLANG\Bin\ArmAsm" --Via ".\objects\startup._ia"
"C:\Users\IanIshikawa\AppData\Local\Keil_v5\ARM\ARMCLANG\Bin\ArmAsm" --Via ".\objects\utils._ia"
"C:\Users\IanIshikawa\AppData\Local\Keil_v5\ARM\ARMCLANG\Bin\ArmLink" --Via ".\Objects\gpio.lnp"
